spring:
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true # print with System out
        format_sql: true

logging:  # print with logger
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
